server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level [%X{correlationId}] %logger{20} - %msg%n"
